# -*- coding: utf-8 -*-
"""Lab_exam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MezCdiEsSYiOjcRBbegHkam9ElnShz9L
"""

print("Courses and Credits")
print("HPC -4")
print("Seminar -1")
print("Capstone Design -1")
print("DevOps -3")
print("SPM -3")
print("Undergrad Research-2")
print("Communications-2")
print("Carrer Skills for IT companies-2")